[package]
name = "ap-fossilizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.8", features = ["derive", "env", "cargo"] }
flate2 = "1.0.26"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
tar = "0.4.38"
